# Generated by Django 5.2.3 on 2025-06-23 14:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default.png', null=True, storage=users.models.CustomFileSystemStorage(), upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
